# Numpy básico

In [46]:
import numpy as np

#creación array
array = np.array([[1,2,3],[4,5,6]])
print(array)

#creación array con elementos tipo float
array_float = np.array([[1,2,3],[4,5,6]], dtype=np.float64)
print(array_float)

#creación array de ceros
array_zeros = np.zeros((2,2))
print(array_zeros)

#creación array de unos
array_ones = np.ones((2,2))
print(array_ones)

#creación array con diagonal de unos
array_diag = np.eye(2,2)
print(array_diag)

#creación array relleno con un valor
array_full = np.full((2,2), 3)
print(array_full)


[[1 2 3]
 [4 5 6]]
[[1. 2. 3.]
 [4. 5. 6.]]
[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[1. 0.]
 [0. 1.]]
[[3 3]
 [3 3]]


In [47]:

array_filtrar = np.array([[11,12,13],[21,22,23],[31,32,33],[41,42,43]])
print(array_filtrar)

#se filtra y se crea un nuevo array booleano
filtro = (array_filtrar > 15)
print(filtro)

#si se cumple se pone A y si no, B
np.where(array_filtrar>15, 'A', 'B')

#indica true si algún valor es distinto de 0, si está "vacío" es false
array_zeros.any()

#indica true si no hay ningún elemento = 0
array_filtrar.all()

[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]
[[False False False]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


True

In [48]:
#división de array, filas 0-1 y cols 1-2, [inicio, final)
slice = array_filtrar[0:2,1:3] 
print(slice)

#redefinición de un slice, no se modifica el original
slice2 = np.array(slice)

#concatenar arrays (axis=0 cols, axis=1 filas)
np.concatenate([array_zeros,array_ones], axis=0)


[[12 13]
 [22 23]]


array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

In [49]:
#creación de array aleatorio
array_random = np.random.randn(2,5)

#cálculo de media
print(array_random.mean())

#cálculo de media de cada fila (axis=0 cols, axis=1 filas)
print(array_random.mean(axis=1))

#orden menor a mayor
array_random.sort()

#obtener array con elementos únicos a partir de otro array
array_unique = np.array([1,2,4,1,6,3,2,7,2,1,3,4,1,2,4,5,2,5,3,6,4])
print(np.unique(array_unique))


-0.19018142149971815
[-0.46510141  0.08473857]
[1 2 3 4 5 6 7]


In [50]:
serie1 = np.array([1,2,3])
serie2 = np.array([3,4,5])

#intersección y unión de elementos
print(np.intersect1d(serie1,serie2))
print(np.union1d(serie1,serie2))

#está en serie 1 pero no en serie 2
print(np.setdiff1d(serie1,serie2))

[3]
[1 2 3 4 5]
[1 2]


In [51]:
#propagación de un array (a partir de una fila se crea un array)
base = np.zeros((5,5)) #dimensiones
fila = np.array([1,2,3,4,5]) #fila

base = base + fila
print(base)

[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]
